kind: Service
apiVersion: v1
metadata:
  name: ocp-samples-git
  namespace: demo
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  selector:
    app: ocp-samples-git
    deploymentconfig: ocp-samples-git
